# GoReleaser configuration for Neev CLI
# This configuration builds and releases binaries for multiple platforms
# Supports: Darwin (Intel/ARM64), Linux, and Windows

version: 1

project_name: neev
dist: dist

builds:
  - id: "neev"
    main: ./cli/main.go
    binary: neev
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/neev-kit/neev/cli/cmd.Version={{.Version}}
      - -X github.com/neev-kit/neev/cli/cmd.Commit={{.Commit}}
      - -X github.com/neev-kit/neev/cli/cmd.Date={{.Date}}

archives:
  - id: "default"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: neev-kit
    name: neev
  draft: false
  prerelease: false
  name_template: 'Release {{.Version}}'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^style:"
      - "^ci:"
