package bridge

import (
	"fmt"
	"strings"
)

// FormatSlashCommand wraps context in a slash-command format for IDE integration.
// Returns markdown formatted as a generic slash command for easy copy-paste into chat.
func FormatSlashCommand(context string) string {
	var builder strings.Builder

	builder.WriteString("```markdown\n")
	builder.WriteString("/context\n")
	builder.WriteString("\n")
	builder.WriteString(context)
	builder.WriteString("\n")
	builder.WriteString("```\n")

	return builder.String()
}

// FormatHandoffPrompt wraps context as a handoff prompt for specialized agent roles.
// Returns formatted prompt for chat-based agent systems.
func FormatHandoffPrompt(role string, context string, agentInstructions string) string {
	var builder strings.Builder

	builder.WriteString(fmt.Sprintf("# Slash Command: /neev-handoff-%s\n\n", strings.ToLower(role)))
	builder.WriteString(fmt.Sprintf("**Role:** %s\n\n", role))
	builder.WriteString("## Context\n\n")
	builder.WriteString(context)
	builder.WriteString("\n\n")

	if agentInstructions != "" {
		builder.WriteString("## Instructions\n\n")
		builder.WriteString(agentInstructions)
		builder.WriteString("\n\n")
	}

	builder.WriteString("---\n")
	builder.WriteString("*Generated by Neev for spec-driven development*\n")

	return builder.String()
}

// FormatHandoffMarkdown wraps the handoff prompt in markdown code fence for copy-paste.
func FormatHandoffMarkdown(prompt string) string {
	return fmt.Sprintf("```markdown\n%s\n```\n", prompt)
}
